name: flexible
description: Flutter UI scalable layout scheme.
version: 0.0.1
author: songfei <songfei.org@gmail.com>
homepage: https://github.com/songfei/flutter_flexible

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter: